[package]
name = "cad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.34.0"
glutin = "0.31.3"
glutin-winit = "0.4.2"
winit = "0.29.13"
