pub mod add_bezier_c2;
pub mod bezier_c2_bernstein_points;
pub mod bezier_c2_details;
pub mod rename_bezier_c2;
pub mod add_point_to_bezier_c2;
pub mod delete_bezier_c2_points;
pub mod set_bezier_c2_draw_b_spline_polygon;
pub mod set_bezier_c2_draw_bernstein_polygon;
pub mod set_bezier_c2_draw_bernstein_points;