pub mod add_bezier_c0_on_bezier_c0_created;
pub mod add_point_to_bezier_c0_on_point_added_to_bezier_c0;
pub mod delete_bezier_c0_point_on_bezier_c0_points_deleted;
pub mod update_bezier_c0_points_on_bezier_c0_point_moved;
pub mod delete_bezier_c0_on_bezier_c0_deleted;
pub mod set_draw_polygon_on_bezier_c0_draw_polygon_set;