pub mod add_bezier_c2_on_bezier_c2_created;
pub mod add_point_to_bezier_c2_on_point_added_to_bezier_c2;
pub mod set_draw_bernstein_points_on_bezier_c2_draw_bernstein_points_set;
pub mod set_draw_bernstein_polygon_on_bezier_c2_draw_bernstein_polygon_set;
pub mod set_draw_b_spline_polygon_on_bezier_c2_draw_b_spline_polygon_set;
pub mod delete_bezier_c2_points_on_bezier_c2_points_deleted;